apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: 759386766154.dkr.ecr.us-east-1.amazonaws.com/project:v0.3
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: employees-secret
            - configMapRef:
                name: my-configmap
            