apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: 876560225863.dkr.ecr.us-east-1.amazonaws.com/mysql:my_APP_latest
          envFrom:
          - configMapRef:
              name: app-config
          env:
          - name: DBPWD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DBPWD
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DBUSER
          ports:
          - containerPort: 8080