apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: 976199020745.dkr.ecr.us-east-1.amazonaws.com/clo835_project:my_app_latest
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "mysql-service"
            - name: DBPORT
              value: "3306"
            - name: DATABASE
              value: "employees"
            - name: DBPWD
              value: "password"
            - name: DBUSER
              value: "root"