apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 namespace: final 
 name: webapp-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: webapp-deployment
 minReplicas: 3
 maxReplicas: 10
 targetCPUUtilizationPercentage: 5
 
