apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data1
  namespace: final 
  annotations:
    StorageClass: gp2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi