apiVersion: v1
kind: Secret
metadata:
  namespace: final
  name: employees-secret
data:
  DBHOST: bXlzcWwtc2VydmljZQ==
  DBPORT: MzMwNg==
  DATABASE: ZW1wbG95ZWVz
  DBPWD: cGFzc3dvcmQ=
  DBUSER: cm9vdA==
  aws_access_key_id: QVNJQTNCVEgyUE5GS0JLV0pBWEE=
  aws_secret_access_key: YUIzRDBMVFhJdG5PUXFaU3lhRDBNN3cwMGdzK3plUXdabzY0TE9uTVM=
  aws_session_token: SVFvSmIzSnBHaW5fZWMxS0xJZktLV2ZjUWFDWFZ6LXdlbHNRLTJKSDFFVU9DUVQtT2lqSkg1ZjByYzFZacFzUDVab3AwQWI0S09hek80T2RRckxNbUZYSTJOTUFJZ2FxbmU1dXZjNkNPeVU2SVpTQ3daWFBLKyszTWF4Vkw0cXJnSUliUkFBZ2d3M1ROUWUxNTQiRExRVkVkRGJHQzA4SGwwVk15cUxBaUxrTjdnc3gremVRckxNbUZYSTJOTUFJZ2FxbmU1dXZjNkNPeVU2SVpTQ3daWFBLKyszTWF4VkxNU1JFSnFkRkJnM20rTV9vYUFJMVhtS1RMRGhWTHFtSUV5dFE0dEF4NjRURWhzUW9OMkl2ZHUvRUZFY2JEZnIrbU9hQlh2MFNlMGxYMTlTVTJlbkh2VEZLWkx4cWhkT1FIdC90Ym5yank5NWl4eWk1M25Rb040SWIwRjNyK21PYUJYdjBTZTBMNzFVM0hzUmtXMEVWcEZLWERYeWV1aklNK0hWRkRLWlFtL2JUU1JjWURqUXlWaEhGb29sWUVHY0lWRFd3U0orM1dZWmhjTDA4d2dsQTFRbS9iVFNyQ1lEalF5VmhIRkZLWEZkUitXWWhjTDA4d2dsQTFRbS9iVFNyQ1lEalF5VmhIRkZLWllIQ0VjQW9rdmR1VWsrdFFlTFhxYWhxK3RYVit4U2hoWFUrc1JkR3J0Z1V6VGtsdVhPM3d3c25LUFZKdzIzemxpMFFyV2I0amRqUkFyUWZud0EwT3FGdlo0bFF1Vm0yYnkrczFUcjlDZDQwWHJaVzhiTjR0d3dmcXdnbEF1L1FWTS9iNFZtMmJ5NnoxVHJ0Q2Q0MFhyWldOKEpvem1EN1ZPMDUzVXRIRU5KcHZsUkF6a1JqREJoK2l3QmpxZEFlN2ZvSXUrdm5DenJFc1NqcUxPc2prWmhwaEZicW5hL0VpTktIdllOVU45K2hDTFM3WmNRMjhDdklPTFdESXF6b2VVWlROZVF2N01BcUxTNXZlV01IanZSSTJ6NVFlY043NUk5MWQwQnZ1azFHazJNcWQyc214dGIrN2pnVkh3b3JjV3VYTzJjPQ==
