apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: final 
spec:
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      # nodePort: 32090
  type: LoadBalancer